build/code_logo.png: src/code.svg
	inkscape -e build/code_logo_full.png -D -j -i Code_Logo_Full 	src/code.svg
	inkscape -e build/code_logo.png 		 -D -j -i Code_Logo 			src/code.svg

clean:
	rm -rf build/*
